Repository NktCHRN/CG_Labs, pull requests merged in 2023-03, with the labels that each got.

#2 Base classes and structures
  .gitignore
  Lab1/Lab1.ConsoleApp/Program.cs
  Lab1/Lab1.RayTracer/CGMath.cs
  Lab1/Lab1.RayTracer/Class1.cs
  Lab1/Lab1.RayTracer/Ray.cs
  Lab1/Lab1.RayTracer/Scene.cs
  Lab1/Lab1.RayTracer/SceneObjects/BaseSceneObject.cs
  Lab1/Lab1.RayTracer/SceneObjects/Camera.cs
  Lab1/Lab1.RayTracer/SceneObjects/DirectionLight.cs
  Lab1/Lab1.RayTracer/SceneObjects/Disk.cs
  Lab1/Lab1.RayTracer/SceneObjects/ISceneObject.cs
  Lab1/Lab1.RayTracer/SceneObjects/Plane.cs
  Lab1/Lab1.RayTracer/Vector3f.cs
  Lab1/Lab1.sln
Labels: new features

#11 Implement Quaternion
  Lab1/Lab1.RayTracer/Quaternion.cs
  Lab1/Lab1.RayTracer/SceneObjects/BaseSceneObject.cs
  Lab1/Lab1.RayTracer/Vector3f.cs
Labels: enhancement

#13 fix plane intersection
  Lab1/Lab1.RayTracer/SceneObjects/Plane.cs
Labels: bug

#16 Fix bugs with reversed X in final images
  Lab1/Lab1.ConsoleApp/Program.cs
  Lab1/Lab1.RayTracer/SceneObjects/Camera.cs
Labels: bug

#17 Fix the camera rotation
  Lab1/Lab1.RayTracer/SceneObjects/BaseSceneObject.cs
  Lab1/Lab1.RayTracer/SceneObjects/Camera.cs
Labels: bug

#19 Refactored Scene.Render code and added a new Unit test
  Lab1/Lab1.RayTracer.Tests/SceneTests.cs
  Lab1/Lab1.RayTracer/Lab1.RayTracer.csproj
  Lab1/Lab1.RayTracer/Scene.cs
  Lab1/Lab1.RayTracer/SceneObjects/Sphere.cs
Labels: new features

#20 Changed radius to property in Disk
  Lab1/Lab1.RayTracer/SceneObjects/Disk.cs
Labels: bug
